"""bootstrap qc runs schema

Revision ID: d38aff65e4e3
Revises:
Create Date: 2026-05-25 11:39:51.466067

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d38aff65e4e3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qc_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_name", sa.String(length=255), nullable=False),
        sa.Column("sample_name", sa.String(length=255), nullable=True),
        sa.Column("workflow_name", sa.String(length=100), nullable=False),
        sa.Column("workflow_engine", sa.String(length=50), nullable=False),
        sa.Column("workflow_version", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="qc_run_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("input_path", sa.Text(), nullable=True),
        sa.Column("output_dir", sa.Text(), nullable=True),
        sa.Column("report_path", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qc_runs_run_name"), "qc_runs", ["run_name"], unique=False)
    op.create_index(
        op.f("ix_qc_runs_sample_name"), "qc_runs", ["sample_name"], unique=False
    )
    op.create_index(op.f("ix_qc_runs_status"), "qc_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_qc_runs_workflow_engine"), "qc_runs", ["workflow_engine"], unique=False
    )
    op.create_index(
        op.f("ix_qc_runs_workflow_name"), "qc_runs", ["workflow_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qc_runs_workflow_name"), table_name="qc_runs")
    op.drop_index(op.f("ix_qc_runs_workflow_engine"), table_name="qc_runs")
    op.drop_index(op.f("ix_qc_runs_status"), table_name="qc_runs")
    op.drop_index(op.f("ix_qc_runs_sample_name"), table_name="qc_runs")
    op.drop_index(op.f("ix_qc_runs_run_name"), table_name="qc_runs")
    op.drop_table("qc_runs")
    # ### end Alembic commands ###
